# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prosper.ui'
#
# Created: Wed Mar 21 19:38:04 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 623)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(405, 600))
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(True)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks|QtGui.QMainWindow.ForceTabbedDocks|QtGui.QMainWindow.VerticalTabs)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 405, 550))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_manual = QtGui.QWidget()
        self.tab_manual.setEnabled(False)
        self.tab_manual.setObjectName(_fromUtf8("tab_manual"))
        self.spinBox_hpdl_limit = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdl_limit.setGeometry(QtCore.QRect(120, 190, 60, 25))
        self.spinBox_hpdl_limit.setSuffix(_fromUtf8(""))
        self.spinBox_hpdl_limit.setMaximum(300)
        self.spinBox_hpdl_limit.setObjectName(_fromUtf8("spinBox_hpdl_limit"))
        self.spinBox_hpdl_aspirate_volume = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdl_aspirate_volume.setGeometry(QtCore.QRect(9, 110, 71, 25))
        self.spinBox_hpdl_aspirate_volume.setSuffix(_fromUtf8(""))
        self.spinBox_hpdl_aspirate_volume.setMaximum(9999)
        self.spinBox_hpdl_aspirate_volume.setObjectName(_fromUtf8("spinBox_hpdl_aspirate_volume"))
        self.spinBox_hpdl_dispense_volume = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdl_dispense_volume.setGeometry(QtCore.QRect(109, 110, 71, 25))
        self.spinBox_hpdl_dispense_volume.setSuffix(_fromUtf8(""))
        self.spinBox_hpdl_dispense_volume.setMaximum(9999)
        self.spinBox_hpdl_dispense_volume.setObjectName(_fromUtf8("spinBox_hpdl_dispense_volume"))
        self.pushButton_hpdl_dispense = QtGui.QPushButton(self.tab_manual)
        self.pushButton_hpdl_dispense.setGeometry(QtCore.QRect(100, 140, 90, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Gtk-go-up.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hpdl_dispense.setIcon(icon)
        self.pushButton_hpdl_dispense.setObjectName(_fromUtf8("pushButton_hpdl_dispense"))
        self.label_14 = QtGui.QLabel(self.tab_manual)
        self.label_14.setGeometry(QtCore.QRect(0, 190, 101, 21))
        self.label_14.setAutoFillBackground(False)
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.pushButton_hpdl_aspirate = QtGui.QPushButton(self.tab_manual)
        self.pushButton_hpdl_aspirate.setGeometry(QtCore.QRect(0, 140, 92, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Gtk-go-down.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hpdl_aspirate.setIcon(icon1)
        self.pushButton_hpdl_aspirate.setObjectName(_fromUtf8("pushButton_hpdl_aspirate"))
        self.comboBox_valvel = QtGui.QComboBox(self.tab_manual)
        self.comboBox_valvel.setGeometry(QtCore.QRect(60, 10, 80, 30))
        self.comboBox_valvel.setObjectName(_fromUtf8("comboBox_valvel"))
        self.comboBox_valvel.addItem(_fromUtf8(""))
        self.comboBox_valvel.addItem(_fromUtf8(""))
        self.comboBox_valvel.addItem(_fromUtf8(""))
        self.comboBox_valvel.addItem(_fromUtf8(""))
        self.comboBox_valvel.addItem(_fromUtf8(""))
        self.comboBox_valvel.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.tab_manual)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 91, 20))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.spinBox_hpdl_dispense_speed = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdl_dispense_speed.setGeometry(QtCore.QRect(109, 60, 71, 25))
        self.spinBox_hpdl_dispense_speed.setSuffix(_fromUtf8(""))
        self.spinBox_hpdl_dispense_speed.setMaximum(10000)
        self.spinBox_hpdl_dispense_speed.setObjectName(_fromUtf8("spinBox_hpdl_dispense_speed"))
        self.spinBox_hpdl_aspirate_speed = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdl_aspirate_speed.setGeometry(QtCore.QRect(9, 60, 71, 25))
        self.spinBox_hpdl_aspirate_speed.setSuffix(_fromUtf8(""))
        self.spinBox_hpdl_aspirate_speed.setMaximum(10000)
        self.spinBox_hpdl_aspirate_speed.setObjectName(_fromUtf8("spinBox_hpdl_aspirate_speed"))
        self.label_4 = QtGui.QLabel(self.tab_manual)
        self.label_4.setGeometry(QtCore.QRect(0, 90, 91, 16))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.spinBox_hpdr_limit = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdr_limit.setGeometry(QtCore.QRect(330, 190, 60, 25))
        self.spinBox_hpdr_limit.setSuffix(_fromUtf8(""))
        self.spinBox_hpdr_limit.setMaximum(300)
        self.spinBox_hpdr_limit.setObjectName(_fromUtf8("spinBox_hpdr_limit"))
        self.spinBox_hpdr_aspirate_volume = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdr_aspirate_volume.setGeometry(QtCore.QRect(219, 110, 71, 25))
        self.spinBox_hpdr_aspirate_volume.setStyleSheet(_fromUtf8(""))
        self.spinBox_hpdr_aspirate_volume.setSuffix(_fromUtf8(""))
        self.spinBox_hpdr_aspirate_volume.setMaximum(9999)
        self.spinBox_hpdr_aspirate_volume.setObjectName(_fromUtf8("spinBox_hpdr_aspirate_volume"))
        self.spinBox_hpdr_dispense_speed = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdr_dispense_speed.setGeometry(QtCore.QRect(319, 60, 71, 25))
        self.spinBox_hpdr_dispense_speed.setSuffix(_fromUtf8(""))
        self.spinBox_hpdr_dispense_speed.setMaximum(10000)
        self.spinBox_hpdr_dispense_speed.setObjectName(_fromUtf8("spinBox_hpdr_dispense_speed"))
        self.pushButton_hpdr_dispense = QtGui.QPushButton(self.tab_manual)
        self.pushButton_hpdr_dispense.setGeometry(QtCore.QRect(310, 140, 90, 30))
        self.pushButton_hpdr_dispense.setIcon(icon)
        self.pushButton_hpdr_dispense.setObjectName(_fromUtf8("pushButton_hpdr_dispense"))
        self.spinBox_hpdr_aspirate_speed = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdr_aspirate_speed.setGeometry(QtCore.QRect(219, 60, 71, 25))
        self.spinBox_hpdr_aspirate_speed.setSuffix(_fromUtf8(""))
        self.spinBox_hpdr_aspirate_speed.setMaximum(10000)
        self.spinBox_hpdr_aspirate_speed.setObjectName(_fromUtf8("spinBox_hpdr_aspirate_speed"))
        self.spinBox_hpdr_dispense_volume = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_hpdr_dispense_volume.setGeometry(QtCore.QRect(319, 110, 71, 25))
        self.spinBox_hpdr_dispense_volume.setSuffix(_fromUtf8(""))
        self.spinBox_hpdr_dispense_volume.setMaximum(9999)
        self.spinBox_hpdr_dispense_volume.setObjectName(_fromUtf8("spinBox_hpdr_dispense_volume"))
        self.pushButton_hpdr_aspirate = QtGui.QPushButton(self.tab_manual)
        self.pushButton_hpdr_aspirate.setGeometry(QtCore.QRect(210, 140, 92, 30))
        self.pushButton_hpdr_aspirate.setIcon(icon1)
        self.pushButton_hpdr_aspirate.setObjectName(_fromUtf8("pushButton_hpdr_aspirate"))
        self.comboBox_valver = QtGui.QComboBox(self.tab_manual)
        self.comboBox_valver.setGeometry(QtCore.QRect(270, 10, 80, 30))
        self.comboBox_valver.setObjectName(_fromUtf8("comboBox_valver"))
        self.comboBox_valver.addItem(_fromUtf8(""))
        self.comboBox_valver.addItem(_fromUtf8(""))
        self.comboBox_valver.addItem(_fromUtf8(""))
        self.comboBox_valver.addItem(_fromUtf8(""))
        self.comboBox_valver.addItem(_fromUtf8(""))
        self.comboBox_valver.addItem(_fromUtf8(""))
        self.line = QtGui.QFrame(self.tab_manual)
        self.line.setGeometry(QtCore.QRect(180, 0, 30, 231))
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.tab_manual)
        self.line_2.setGeometry(QtCore.QRect(0, 220, 401, 20))
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.tab_manual)
        self.line_3.setGeometry(QtCore.QRect(75, 40, 45, 121))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.tab_manual)
        self.line_4.setGeometry(QtCore.QRect(285, 40, 45, 121))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.comboBox_valve1 = QtGui.QComboBox(self.tab_manual)
        self.comboBox_valve1.setGeometry(QtCore.QRect(70, 240, 48, 30))
        self.comboBox_valve1.setObjectName(_fromUtf8("comboBox_valve1"))
        self.comboBox_valve1.addItem(_fromUtf8(""))
        self.comboBox_valve1.addItem(_fromUtf8(""))
        self.comboBox_valve2 = QtGui.QComboBox(self.tab_manual)
        self.comboBox_valve2.setGeometry(QtCore.QRect(160, 240, 48, 30))
        self.comboBox_valve2.setObjectName(_fromUtf8("comboBox_valve2"))
        self.comboBox_valve2.addItem(_fromUtf8(""))
        self.comboBox_valve2.addItem(_fromUtf8(""))
        self.comboBox_valve3 = QtGui.QComboBox(self.tab_manual)
        self.comboBox_valve3.setGeometry(QtCore.QRect(250, 240, 48, 30))
        self.comboBox_valve3.setObjectName(_fromUtf8("comboBox_valve3"))
        self.comboBox_valve3.addItem(_fromUtf8(""))
        self.comboBox_valve3.addItem(_fromUtf8(""))
        self.comboBox_valve4 = QtGui.QComboBox(self.tab_manual)
        self.comboBox_valve4.setGeometry(QtCore.QRect(340, 240, 36, 30))
        self.comboBox_valve4.setObjectName(_fromUtf8("comboBox_valve4"))
        self.comboBox_valve4.addItem(_fromUtf8(""))
        self.comboBox_valve4.addItem(_fromUtf8(""))
        self.comboBox_valve4.addItem(_fromUtf8(""))
        self.comboBox_valve4.addItem(_fromUtf8(""))
        self.comboBox_valve4.addItem(_fromUtf8(""))
        self.comboBox_valve4.addItem(_fromUtf8(""))
        self.comboBox_valve4.addItem(_fromUtf8(""))
        self.comboBox_valve4.addItem(_fromUtf8(""))
        self.line_5 = QtGui.QFrame(self.tab_manual)
        self.line_5.setGeometry(QtCore.QRect(0, 270, 401, 20))
        self.line_5.setLineWidth(4)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label = QtGui.QLabel(self.tab_manual)
        self.label.setGeometry(QtCore.QRect(0, 0, 59, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_10 = QtGui.QLabel(self.tab_manual)
        self.label_10.setGeometry(QtCore.QRect(200, 0, 59, 15))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab_manual)
        self.label_11.setGeometry(QtCore.QRect(0, 250, 59, 15))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_manual)
        self.label_12.setGeometry(QtCore.QRect(0, 290, 131, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_ace_getback = QtGui.QPushButton(self.tab_manual)
        self.pushButton_ace_getback.setGeometry(QtCore.QRect(130, 310, 140, 30))
        self.pushButton_ace_getback.setObjectName(_fromUtf8("pushButton_ace_getback"))
        self.comboBox_cartridge = QtGui.QComboBox(self.tab_manual)
        self.comboBox_cartridge.setGeometry(QtCore.QRect(180, 370, 90, 30))
        self.comboBox_cartridge.setEditable(True)
        self.comboBox_cartridge.setObjectName(_fromUtf8("comboBox_cartridge"))
        self.pushButton_acel_put_cartridge = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acel_put_cartridge.setGeometry(QtCore.QRect(80, 370, 51, 30))
        self.pushButton_acel_put_cartridge.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Gtk-top-left.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_acel_put_cartridge.setIcon(icon2)
        self.pushButton_acel_put_cartridge.setObjectName(_fromUtf8("pushButton_acel_put_cartridge"))
        self.pushButton_acer_put_cartridge = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acer_put_cartridge.setGeometry(QtCore.QRect(269, 370, 51, 30))
        self.pushButton_acer_put_cartridge.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Gtk-top-right.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_acer_put_cartridge.setIcon(icon3)
        self.pushButton_acer_put_cartridge.setObjectName(_fromUtf8("pushButton_acer_put_cartridge"))
        self.pushButton_acel_getback = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acel_getback.setGeometry(QtCore.QRect(80, 310, 50, 30))
        self.pushButton_acel_getback.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Gtk-bottom-right.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_acel_getback.setIcon(icon4)
        self.pushButton_acel_getback.setObjectName(_fromUtf8("pushButton_acel_getback"))
        self.pushButton_acer_getback = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acer_getback.setGeometry(QtCore.QRect(270, 310, 50, 30))
        self.pushButton_acer_getback.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/Gtk-bottom-left.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_acer_getback.setIcon(icon5)
        self.pushButton_acer_getback.setObjectName(_fromUtf8("pushButton_acer_getback"))
        self.pushButton_ace_gripperl = QtGui.QPushButton(self.tab_manual)
        self.pushButton_ace_gripperl.setGeometry(QtCore.QRect(0, 370, 40, 30))
        self.pushButton_ace_gripperl.setText(_fromUtf8(""))
        self.pushButton_ace_gripperl.setIcon(icon)
        self.pushButton_ace_gripperl.setObjectName(_fromUtf8("pushButton_ace_gripperl"))
        self.pushButton_ace_gripperr = QtGui.QPushButton(self.tab_manual)
        self.pushButton_ace_gripperr.setGeometry(QtCore.QRect(360, 370, 40, 30))
        self.pushButton_ace_gripperr.setText(_fromUtf8(""))
        self.pushButton_ace_gripperr.setIcon(icon)
        self.pushButton_ace_gripperr.setObjectName(_fromUtf8("pushButton_ace_gripperr"))
        self.line_6 = QtGui.QFrame(self.tab_manual)
        self.line_6.setGeometry(QtCore.QRect(0, 400, 401, 20))
        self.line_6.setLineWidth(4)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_trays = QtGui.QLabel(self.tab_manual)
        self.label_trays.setGeometry(QtCore.QRect(0, 420, 31, 16))
        self.label_trays.setObjectName(_fromUtf8("label_trays"))
        self.pushButton_tray_load = QtGui.QPushButton(self.tab_manual)
        self.pushButton_tray_load.setGeometry(QtCore.QRect(120, 430, 81, 30))
        self.pushButton_tray_load.setIcon(icon)
        self.pushButton_tray_load.setObjectName(_fromUtf8("pushButton_tray_load"))
        self.pushButton_tray_unload = QtGui.QPushButton(self.tab_manual)
        self.pushButton_tray_unload.setGeometry(QtCore.QRect(40, 430, 81, 30))
        self.pushButton_tray_unload.setIcon(icon1)
        self.pushButton_tray_unload.setObjectName(_fromUtf8("pushButton_tray_unload"))
        self.label_3 = QtGui.QLabel(self.tab_manual)
        self.label_3.setGeometry(QtCore.QRect(100, 40, 91, 20))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_8 = QtGui.QLabel(self.tab_manual)
        self.label_8.setGeometry(QtCore.QRect(210, 40, 91, 20))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_manual)
        self.label_9.setGeometry(QtCore.QRect(310, 40, 91, 20))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_5 = QtGui.QLabel(self.tab_manual)
        self.label_5.setGeometry(QtCore.QRect(100, 90, 91, 16))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_manual)
        self.label_6.setGeometry(QtCore.QRect(210, 90, 91, 16))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab_manual)
        self.label_7.setGeometry(QtCore.QRect(310, 90, 91, 16))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_15 = QtGui.QLabel(self.tab_manual)
        self.label_15.setGeometry(QtCore.QRect(200, 190, 101, 21))
        self.label_15.setAutoFillBackground(False)
        self.label_15.setTextFormat(QtCore.Qt.RichText)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pushButton_acel_open = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acel_open.setGeometry(QtCore.QRect(0, 310, 40, 30))
        self.pushButton_acel_open.setObjectName(_fromUtf8("pushButton_acel_open"))
        self.pushButton_acel_close = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acel_close.setGeometry(QtCore.QRect(40, 310, 40, 30))
        self.pushButton_acel_close.setObjectName(_fromUtf8("pushButton_acel_close"))
        self.pushButton_acer_open = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acer_open.setGeometry(QtCore.QRect(320, 310, 40, 30))
        self.pushButton_acer_open.setObjectName(_fromUtf8("pushButton_acer_open"))
        self.pushButton_acer_close = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acer_close.setGeometry(QtCore.QRect(360, 310, 40, 30))
        self.pushButton_acer_close.setObjectName(_fromUtf8("pushButton_acer_close"))
        self.pushButton_acel_init = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acel_init.setGeometry(QtCore.QRect(0, 340, 40, 30))
        self.pushButton_acel_init.setObjectName(_fromUtf8("pushButton_acel_init"))
        self.pushButton_acel_default = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acel_default.setGeometry(QtCore.QRect(40, 340, 40, 30))
        self.pushButton_acel_default.setObjectName(_fromUtf8("pushButton_acel_default"))
        self.pushButton_acer_init = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acer_init.setGeometry(QtCore.QRect(320, 340, 40, 30))
        self.pushButton_acer_init.setObjectName(_fromUtf8("pushButton_acer_init"))
        self.pushButton_acer_default = QtGui.QPushButton(self.tab_manual)
        self.pushButton_acer_default.setGeometry(QtCore.QRect(360, 340, 40, 30))
        self.pushButton_acer_default.setObjectName(_fromUtf8("pushButton_acer_default"))
        self.label_trays_2 = QtGui.QLabel(self.tab_manual)
        self.label_trays_2.setGeometry(QtCore.QRect(210, 420, 131, 16))
        self.label_trays_2.setObjectName(_fromUtf8("label_trays_2"))
        self.checkBox_OUT1 = QtGui.QCheckBox(self.tab_manual)
        self.checkBox_OUT1.setEnabled(False)
        self.checkBox_OUT1.setGeometry(QtCore.QRect(220, 440, 41, 20))
        self.checkBox_OUT1.setStyleSheet(_fromUtf8("QCheckBox::indicator \n"
"{\n"
"width:16px;\n"
"height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"  {\n"
"    image: url(:/images/images/check_on.svg);\n"
"  }\n"
"  QCheckBox::indicator:unchecked\n"
"  {\n"
"    image: url(:/images/images/check_off.svg);\n"
"  }\n"
"\n"
""))
        self.checkBox_OUT1.setCheckable(True)
        self.checkBox_OUT1.setChecked(False)
        self.checkBox_OUT1.setTristate(False)
        self.checkBox_OUT1.setObjectName(_fromUtf8("checkBox_OUT1"))
        self.checkBox_OUT2 = QtGui.QCheckBox(self.tab_manual)
        self.checkBox_OUT2.setEnabled(False)
        self.checkBox_OUT2.setGeometry(QtCore.QRect(270, 440, 41, 20))
        self.checkBox_OUT2.setStyleSheet(_fromUtf8("QCheckBox::indicator \n"
"{\n"
"width:16px;\n"
"height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"  {\n"
"    image: url(:/images/images/check_on.svg);\n"
"  }\n"
"  QCheckBox::indicator:unchecked\n"
"  {\n"
"    image: url(:/images/images/check_off.svg);\n"
"  }\n"
"\n"
""))
        self.checkBox_OUT2.setCheckable(True)
        self.checkBox_OUT2.setChecked(False)
        self.checkBox_OUT2.setTristate(False)
        self.checkBox_OUT2.setObjectName(_fromUtf8("checkBox_OUT2"))
        self.checkBox_OUT3 = QtGui.QCheckBox(self.tab_manual)
        self.checkBox_OUT3.setEnabled(False)
        self.checkBox_OUT3.setGeometry(QtCore.QRect(320, 440, 41, 20))
        self.checkBox_OUT3.setStyleSheet(_fromUtf8("QCheckBox::indicator \n"
"{\n"
"width:16px;\n"
"height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"  {\n"
"    image: url(:/images/images/check_on.svg);\n"
"  }\n"
"  QCheckBox::indicator:unchecked\n"
"  {\n"
"    image: url(:/images/images/check_off.svg);\n"
"  }\n"
"\n"
""))
        self.checkBox_OUT3.setCheckable(True)
        self.checkBox_OUT3.setChecked(False)
        self.checkBox_OUT3.setTristate(False)
        self.checkBox_OUT3.setObjectName(_fromUtf8("checkBox_OUT3"))
        self.checkBox_OUT4 = QtGui.QCheckBox(self.tab_manual)
        self.checkBox_OUT4.setEnabled(False)
        self.checkBox_OUT4.setGeometry(QtCore.QRect(370, 440, 41, 20))
        self.checkBox_OUT4.setStyleSheet(_fromUtf8("QCheckBox::indicator \n"
"{\n"
"width:16px;\n"
"height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"  {\n"
"    image: url(:/images/images/check_on.svg);\n"
"  }\n"
"  QCheckBox::indicator:unchecked\n"
"  {\n"
"    image: url(:/images/images/check_off.svg);\n"
"  }\n"
"\n"
""))
        self.checkBox_OUT4.setCheckable(True)
        self.checkBox_OUT4.setChecked(False)
        self.checkBox_OUT4.setTristate(False)
        self.checkBox_OUT4.setObjectName(_fromUtf8("checkBox_OUT4"))
        self.pushButton_racks = QtGui.QPushButton(self.tab_manual)
        self.pushButton_racks.setGeometry(QtCore.QRect(130, 370, 51, 30))
        self.pushButton_racks.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/racks.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_racks.setIcon(icon6)
        self.pushButton_racks.setObjectName(_fromUtf8("pushButton_racks"))
        self.label_trays_3 = QtGui.QLabel(self.tab_manual)
        self.label_trays_3.setGeometry(QtCore.QRect(0, 480, 40, 16))
        self.label_trays_3.setObjectName(_fromUtf8("label_trays_3"))
        self.line_7 = QtGui.QFrame(self.tab_manual)
        self.line_7.setGeometry(QtCore.QRect(0, 460, 401, 20))
        self.line_7.setLineWidth(4)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.checkBox_pumponoff = QtGui.QCheckBox(self.tab_manual)
        self.checkBox_pumponoff.setEnabled(False)
        self.checkBox_pumponoff.setGeometry(QtCore.QRect(40, 490, 71, 21))
        self.checkBox_pumponoff.setStyleSheet(_fromUtf8("QCheckBox::indicator \n"
"{\n"
"width:16px;\n"
"height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"  {\n"
"    image: url(:/images/images/check_on.svg);\n"
"  }\n"
"  QCheckBox::indicator:unchecked\n"
"  {\n"
"    image: url(:/images/images/check_off.svg);\n"
"  }\n"
"\n"
""))
        self.checkBox_pumponoff.setCheckable(True)
        self.checkBox_pumponoff.setChecked(False)
        self.checkBox_pumponoff.setTristate(False)
        self.checkBox_pumponoff.setObjectName(_fromUtf8("checkBox_pumponoff"))
        self.spinBox_pumpflow = QtGui.QSpinBox(self.tab_manual)
        self.spinBox_pumpflow.setGeometry(QtCore.QRect(120, 490, 71, 21))
        self.spinBox_pumpflow.setSuffix(_fromUtf8(""))
        self.spinBox_pumpflow.setMaximum(10000)
        self.spinBox_pumpflow.setObjectName(_fromUtf8("spinBox_pumpflow"))
        self.tabWidget.addTab(self.tab_manual, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.pushButton_launch = QtGui.QPushButton(self.tab_2)
        self.pushButton_launch.setGeometry(QtCore.QRect(290, 410, 111, 70))
        self.pushButton_launch.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/gears.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_launch.setIcon(icon7)
        self.pushButton_launch.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_launch.setObjectName(_fromUtf8("pushButton_launch"))
        self.pushButton_add = QtGui.QPushButton(self.tab_2)
        self.pushButton_add.setGeometry(QtCore.QRect(0, 410, 111, 70))
        self.pushButton_add.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon8)
        self.pushButton_add.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.pushButton_moveup = QtGui.QPushButton(self.tab_2)
        self.pushButton_moveup.setGeometry(QtCore.QRect(110, 410, 71, 35))
        self.pushButton_moveup.setText(_fromUtf8(""))
        self.pushButton_moveup.setIcon(icon)
        self.pushButton_moveup.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_moveup.setObjectName(_fromUtf8("pushButton_moveup"))
        self.pushButton_movedown = QtGui.QPushButton(self.tab_2)
        self.pushButton_movedown.setGeometry(QtCore.QRect(110, 445, 71, 35))
        self.pushButton_movedown.setText(_fromUtf8(""))
        self.pushButton_movedown.setIcon(icon1)
        self.pushButton_movedown.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_movedown.setObjectName(_fromUtf8("pushButton_movedown"))
        self.pushButton_remove = QtGui.QPushButton(self.tab_2)
        self.pushButton_remove.setGeometry(QtCore.QRect(180, 410, 111, 70))
        self.pushButton_remove.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/remove.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_remove.setIcon(icon9)
        self.pushButton_remove.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_remove.setObjectName(_fromUtf8("pushButton_remove"))
        self.listWidget_automation = QtGui.QListWidget(self.tab_2)
        self.listWidget_automation.setGeometry(QtCore.QRect(0, 0, 401, 411))
        self.listWidget_automation.setObjectName(_fromUtf8("listWidget_automation"))
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 480, 111, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(181, 480, 111, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(291, 480, 111, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(405, 0, 395, 550))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_systemview = QtGui.QWidget()
        self.tab_systemview.setEnabled(False)
        self.tab_systemview.setObjectName(_fromUtf8("tab_systemview"))
        self.progressBar_hpdl = QtGui.QProgressBar(self.tab_systemview)
        self.progressBar_hpdl.setGeometry(QtCore.QRect(30, 10, 20, 191))
        self.progressBar_hpdl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_hpdl.setMaximum(2000)
        self.progressBar_hpdl.setProperty("value", 42)
        self.progressBar_hpdl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar_hpdl.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_hpdl.setInvertedAppearance(True)
        self.progressBar_hpdl.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar_hpdl.setObjectName(_fromUtf8("progressBar_hpdl"))
        self.progressBar_hpdr = QtGui.QProgressBar(self.tab_systemview)
        self.progressBar_hpdr.setGeometry(QtCore.QRect(345, 10, 20, 191))
        self.progressBar_hpdr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_hpdr.setMaximum(2000)
        self.progressBar_hpdr.setProperty("value", 42)
        self.progressBar_hpdr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progressBar_hpdr.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_hpdr.setInvertedAppearance(True)
        self.progressBar_hpdr.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar_hpdr.setObjectName(_fromUtf8("progressBar_hpdr"))
        self.label_v1_bg = QtGui.QLabel(self.tab_systemview)
        self.label_v1_bg.setGeometry(QtCore.QRect(0, 220, 91, 91))
        self.label_v1_bg.setText(_fromUtf8(""))
        self.label_v1_bg.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/valve_bg.svg")))
        self.label_v1_bg.setScaledContents(True)
        self.label_v1_bg.setObjectName(_fromUtf8("label_v1_bg"))
        self.label_v2_bg = QtGui.QLabel(self.tab_systemview)
        self.label_v2_bg.setGeometry(QtCore.QRect(100, 220, 91, 91))
        self.label_v2_bg.setText(_fromUtf8(""))
        self.label_v2_bg.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/valve_bg.svg")))
        self.label_v2_bg.setScaledContents(True)
        self.label_v2_bg.setObjectName(_fromUtf8("label_v2_bg"))
        self.label_v3_bg = QtGui.QLabel(self.tab_systemview)
        self.label_v3_bg.setGeometry(QtCore.QRect(200, 220, 91, 91))
        self.label_v3_bg.setText(_fromUtf8(""))
        self.label_v3_bg.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/valve_bg.svg")))
        self.label_v3_bg.setScaledContents(True)
        self.label_v3_bg.setObjectName(_fromUtf8("label_v3_bg"))
        self.label_v4_bg = QtGui.QLabel(self.tab_systemview)
        self.label_v4_bg.setGeometry(QtCore.QRect(300, 220, 91, 91))
        self.label_v4_bg.setText(_fromUtf8(""))
        self.label_v4_bg.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/valve_bg.svg")))
        self.label_v4_bg.setScaledContents(True)
        self.label_v4_bg.setObjectName(_fromUtf8("label_v4_bg"))
        self.label_vr_bg = QtGui.QLabel(self.tab_systemview)
        self.label_vr_bg.setGeometry(QtCore.QRect(230, 10, 91, 91))
        self.label_vr_bg.setText(_fromUtf8(""))
        self.label_vr_bg.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/valve_bg.svg")))
        self.label_vr_bg.setScaledContents(True)
        self.label_vr_bg.setObjectName(_fromUtf8("label_vr_bg"))
        self.label_vl_bg = QtGui.QLabel(self.tab_systemview)
        self.label_vl_bg.setGeometry(QtCore.QRect(70, 10, 91, 91))
        self.label_vl_bg.setText(_fromUtf8(""))
        self.label_vl_bg.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/valve_bg.svg")))
        self.label_vl_bg.setScaledContents(True)
        self.label_vl_bg.setObjectName(_fromUtf8("label_vl_bg"))
        self.label_vl_content = QtGui.QLabel(self.tab_systemview)
        self.label_vl_content.setGeometry(QtCore.QRect(70, 10, 91, 91))
        self.label_vl_content.setText(_fromUtf8(""))
        self.label_vl_content.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/7valve_content.svg")))
        self.label_vl_content.setScaledContents(True)
        self.label_vl_content.setObjectName(_fromUtf8("label_vl_content"))
        self.label_vr_content = QtGui.QLabel(self.tab_systemview)
        self.label_vr_content.setGeometry(QtCore.QRect(230, 10, 91, 91))
        self.label_vr_content.setText(_fromUtf8(""))
        self.label_vr_content.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/7valve_content.svg")))
        self.label_vr_content.setScaledContents(True)
        self.label_vr_content.setObjectName(_fromUtf8("label_vr_content"))
        self.label_v1_content = QtGui.QLabel(self.tab_systemview)
        self.label_v1_content.setGeometry(QtCore.QRect(0, 220, 91, 91))
        self.label_v1_content.setText(_fromUtf8(""))
        self.label_v1_content.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/8valve_content.svg")))
        self.label_v1_content.setScaledContents(True)
        self.label_v1_content.setObjectName(_fromUtf8("label_v1_content"))
        self.label_v2_content = QtGui.QLabel(self.tab_systemview)
        self.label_v2_content.setGeometry(QtCore.QRect(100, 220, 91, 91))
        self.label_v2_content.setText(_fromUtf8(""))
        self.label_v2_content.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/6valve_content.svg")))
        self.label_v2_content.setScaledContents(True)
        self.label_v2_content.setObjectName(_fromUtf8("label_v2_content"))
        self.label_v3_content = QtGui.QLabel(self.tab_systemview)
        self.label_v3_content.setGeometry(QtCore.QRect(200, 220, 91, 91))
        self.label_v3_content.setText(_fromUtf8(""))
        self.label_v3_content.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/6valve_content.svg")))
        self.label_v3_content.setScaledContents(True)
        self.label_v3_content.setObjectName(_fromUtf8("label_v3_content"))
        self.label_v4_content = QtGui.QLabel(self.tab_systemview)
        self.label_v4_content.setGeometry(QtCore.QRect(300, 220, 91, 91))
        self.label_v4_content.setText(_fromUtf8(""))
        self.label_v4_content.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/9valve_content.svg")))
        self.label_v4_content.setScaledContents(True)
        self.label_v4_content.setObjectName(_fromUtf8("label_v4_content"))
        self.label_vl_finger = QtGui.QLabel(self.tab_systemview)
        self.label_vl_finger.setGeometry(QtCore.QRect(70, 10, 91, 91))
        self.label_vl_finger.setText(_fromUtf8(""))
        self.label_vl_finger.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/7valve_finger.svg")))
        self.label_vl_finger.setScaledContents(True)
        self.label_vl_finger.setObjectName(_fromUtf8("label_vl_finger"))
        self.label_vr_finger = QtGui.QLabel(self.tab_systemview)
        self.label_vr_finger.setGeometry(QtCore.QRect(230, 10, 91, 91))
        self.label_vr_finger.setText(_fromUtf8(""))
        self.label_vr_finger.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/7valve_finger.svg")))
        self.label_vr_finger.setScaledContents(True)
        self.label_vr_finger.setObjectName(_fromUtf8("label_vr_finger"))
        self.label_v1_finger = QtGui.QLabel(self.tab_systemview)
        self.label_v1_finger.setGeometry(QtCore.QRect(0, 220, 91, 91))
        self.label_v1_finger.setStyleSheet(_fromUtf8(""))
        self.label_v1_finger.setText(_fromUtf8(""))
        self.label_v1_finger.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/8valve_fingers.svg")))
        self.label_v1_finger.setScaledContents(True)
        self.label_v1_finger.setObjectName(_fromUtf8("label_v1_finger"))
        self.label_v2_finger = QtGui.QLabel(self.tab_systemview)
        self.label_v2_finger.setGeometry(QtCore.QRect(100, 220, 91, 91))
        self.label_v2_finger.setText(_fromUtf8(""))
        self.label_v2_finger.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/6valve_fingers.svg")))
        self.label_v2_finger.setScaledContents(True)
        self.label_v2_finger.setObjectName(_fromUtf8("label_v2_finger"))
        self.label_v3_finger = QtGui.QLabel(self.tab_systemview)
        self.label_v3_finger.setGeometry(QtCore.QRect(200, 220, 91, 91))
        self.label_v3_finger.setText(_fromUtf8(""))
        self.label_v3_finger.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/6valve_fingers.svg")))
        self.label_v3_finger.setScaledContents(True)
        self.label_v3_finger.setObjectName(_fromUtf8("label_v3_finger"))
        self.label_v4_finger = QtGui.QLabel(self.tab_systemview)
        self.label_v4_finger.setGeometry(QtCore.QRect(300, 220, 91, 91))
        self.label_v4_finger.setText(_fromUtf8(""))
        self.label_v4_finger.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/9valve_fingers.svg")))
        self.label_v4_finger.setScaledContents(True)
        self.label_v4_finger.setObjectName(_fromUtf8("label_v4_finger"))
        self.lcdNumber_hpdl = QtGui.QLCDNumber(self.tab_systemview)
        self.lcdNumber_hpdl.setGeometry(QtCore.QRect(70, 130, 91, 71))
        self.lcdNumber_hpdl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_hpdl.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_hpdl.setNumDigits(3)
        self.lcdNumber_hpdl.setDigitCount(3)
        self.lcdNumber_hpdl.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_hpdl.setProperty("value", 42.0)
        self.lcdNumber_hpdl.setProperty("intValue", 42)
        self.lcdNumber_hpdl.setObjectName(_fromUtf8("lcdNumber_hpdl"))
        self.lcdNumber_hpdr = QtGui.QLCDNumber(self.tab_systemview)
        self.lcdNumber_hpdr.setGeometry(QtCore.QRect(230, 130, 91, 71))
        self.lcdNumber_hpdr.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lcdNumber_hpdr.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcdNumber_hpdr.setNumDigits(3)
        self.lcdNumber_hpdr.setDigitCount(3)
        self.lcdNumber_hpdr.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.lcdNumber_hpdr.setProperty("value", 42.0)
        self.lcdNumber_hpdr.setProperty("intValue", 42)
        self.lcdNumber_hpdr.setObjectName(_fromUtf8("lcdNumber_hpdr"))
        self.checkBox_IN = QtGui.QCheckBox(self.tab_systemview)
        self.checkBox_IN.setEnabled(False)
        self.checkBox_IN.setGeometry(QtCore.QRect(10, 490, 101, 20))
        self.checkBox_IN.setStyleSheet(_fromUtf8("QCheckBox::indicator \n"
"{\n"
"width:16px;\n"
"height:16px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"  {\n"
"    image: url(:/images/images/check_on_green.svg);\n"
"  }\n"
"  QCheckBox::indicator:unchecked\n"
"  {\n"
"    image: url(:/images/images/check_off_red.svg);\n"
"  }\n"
"\n"
""))
        self.checkBox_IN.setCheckable(True)
        self.checkBox_IN.setChecked(False)
        self.checkBox_IN.setTristate(False)
        self.checkBox_IN.setObjectName(_fromUtf8("checkBox_IN"))
        self.tabWidget_2.addTab(self.tab_systemview, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_sysinf_hpd = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd.setGeometry(QtCore.QRect(10, 10, 59, 15))
        self.label_sysinf_hpd.setObjectName(_fromUtf8("label_sysinf_hpd"))
        self.label_sysinf_ace = QtGui.QLabel(self.tab)
        self.label_sysinf_ace.setGeometry(QtCore.QRect(10, 200, 59, 15))
        self.label_sysinf_ace.setObjectName(_fromUtf8("label_sysinf_ace"))
        self.label_sysinf_hpd_MCCB = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_MCCB.setGeometry(QtCore.QRect(30, 40, 59, 15))
        self.label_sysinf_hpd_MCCB.setObjectName(_fromUtf8("label_sysinf_hpd_MCCB"))
        self.label_sysinf_ace_transport = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_transport.setGeometry(QtCore.QRect(30, 240, 111, 16))
        self.label_sysinf_ace_transport.setObjectName(_fromUtf8("label_sysinf_ace_transport"))
        self.label_sysinf_ace_clampL = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_clampL.setGeometry(QtCore.QRect(30, 260, 111, 16))
        self.label_sysinf_ace_clampL.setObjectName(_fromUtf8("label_sysinf_ace_clampL"))
        self.label_sysinf_ace_clampR = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_clampR.setGeometry(QtCore.QRect(30, 280, 111, 16))
        self.label_sysinf_ace_clampR.setObjectName(_fromUtf8("label_sysinf_ace_clampR"))
        self.label_sysinf_ace_ISS = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_ISS.setGeometry(QtCore.QRect(220, 220, 81, 16))
        self.label_sysinf_ace_ISS.setObjectName(_fromUtf8("label_sysinf_ace_ISS"))
        self.label_sysinf_ace_RF = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_RF.setGeometry(QtCore.QRect(220, 240, 81, 16))
        self.label_sysinf_ace_RF.setObjectName(_fromUtf8("label_sysinf_ace_RF"))
        self.label_sysinf_ace_TASPE = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_TASPE.setGeometry(QtCore.QRect(220, 260, 81, 16))
        self.label_sysinf_ace_TASPE.setObjectName(_fromUtf8("label_sysinf_ace_TASPE"))
        self.label_sysinf_ace_feeder = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_feeder.setGeometry(QtCore.QRect(220, 280, 81, 16))
        self.label_sysinf_ace_feeder.setObjectName(_fromUtf8("label_sysinf_ace_feeder"))
        self.label_sysinf_ace_MPV = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_MPV.setGeometry(QtCore.QRect(30, 300, 111, 16))
        self.label_sysinf_ace_MPV.setObjectName(_fromUtf8("label_sysinf_ace_MPV"))
        self.label_sysinf_ace_MCCB = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_MCCB.setGeometry(QtCore.QRect(30, 220, 59, 15))
        self.label_sysinf_ace_MCCB.setObjectName(_fromUtf8("label_sysinf_ace_MCCB"))
        self.label_sysinf_hpd_SSM = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_SSM.setGeometry(QtCore.QRect(220, 40, 59, 15))
        self.label_sysinf_hpd_SSM.setObjectName(_fromUtf8("label_sysinf_hpd_SSM"))
        self.label_sysinf_hpd_dispenserL = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_dispenserL.setGeometry(QtCore.QRect(30, 60, 71, 16))
        self.label_sysinf_hpd_dispenserL.setObjectName(_fromUtf8("label_sysinf_hpd_dispenserL"))
        self.label_sysinf_hpd_dispenserR = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_dispenserR.setGeometry(QtCore.QRect(220, 60, 71, 16))
        self.label_sysinf_hpd_dispenserR.setObjectName(_fromUtf8("label_sysinf_hpd_dispenserR"))
        self.label_sysinf_hpd_MCCB_val = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_MCCB_val.setGeometry(QtCore.QRect(150, 40, 59, 15))
        self.label_sysinf_hpd_MCCB_val.setObjectName(_fromUtf8("label_sysinf_hpd_MCCB_val"))
        self.label_sysinf_hpd_dispenserL_val = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_dispenserL_val.setGeometry(QtCore.QRect(150, 60, 59, 15))
        self.label_sysinf_hpd_dispenserL_val.setObjectName(_fromUtf8("label_sysinf_hpd_dispenserL_val"))
        self.label_sysinf_hpd_dispenserR_val = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_dispenserR_val.setGeometry(QtCore.QRect(310, 60, 59, 15))
        self.label_sysinf_hpd_dispenserR_val.setObjectName(_fromUtf8("label_sysinf_hpd_dispenserR_val"))
        self.label_sysinf_hpd_SSM_val = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_SSM_val.setGeometry(QtCore.QRect(310, 40, 59, 15))
        self.label_sysinf_hpd_SSM_val.setObjectName(_fromUtf8("label_sysinf_hpd_SSM_val"))
        self.label_sysinf_ace_MCCB_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_MCCB_val.setGeometry(QtCore.QRect(150, 220, 59, 15))
        self.label_sysinf_ace_MCCB_val.setObjectName(_fromUtf8("label_sysinf_ace_MCCB_val"))
        self.label_sysinf_ace_ISS_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_ISS_val.setGeometry(QtCore.QRect(310, 220, 59, 15))
        self.label_sysinf_ace_ISS_val.setObjectName(_fromUtf8("label_sysinf_ace_ISS_val"))
        self.label_sysinf_ace_RF_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_RF_val.setGeometry(QtCore.QRect(310, 240, 59, 15))
        self.label_sysinf_ace_RF_val.setObjectName(_fromUtf8("label_sysinf_ace_RF_val"))
        self.label_sysinf_ace_transport_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_transport_val.setGeometry(QtCore.QRect(150, 240, 59, 15))
        self.label_sysinf_ace_transport_val.setObjectName(_fromUtf8("label_sysinf_ace_transport_val"))
        self.label_sysinf_ace_clampL_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_clampL_val.setGeometry(QtCore.QRect(150, 260, 59, 15))
        self.label_sysinf_ace_clampL_val.setObjectName(_fromUtf8("label_sysinf_ace_clampL_val"))
        self.label_sysinf_ace_clampR_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_clampR_val.setGeometry(QtCore.QRect(150, 280, 59, 15))
        self.label_sysinf_ace_clampR_val.setObjectName(_fromUtf8("label_sysinf_ace_clampR_val"))
        self.label_sysinf_ace_MPV_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_MPV_val.setGeometry(QtCore.QRect(150, 300, 59, 15))
        self.label_sysinf_ace_MPV_val.setObjectName(_fromUtf8("label_sysinf_ace_MPV_val"))
        self.label_sysinf_ace_TASPE_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_TASPE_val.setGeometry(QtCore.QRect(310, 260, 59, 15))
        self.label_sysinf_ace_TASPE_val.setObjectName(_fromUtf8("label_sysinf_ace_TASPE_val"))
        self.label_sysinf_ace_feeder_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_feeder_val.setGeometry(QtCore.QRect(310, 280, 59, 15))
        self.label_sysinf_ace_feeder_val.setObjectName(_fromUtf8("label_sysinf_ace_feeder_val"))
        self.pushButton_sys_inf = QtGui.QPushButton(self.tab)
        self.pushButton_sys_inf.setGeometry(QtCore.QRect(290, 10, 92, 27))
        self.pushButton_sys_inf.setObjectName(_fromUtf8("pushButton_sys_inf"))
        self.label_sysinf_ace_valve1 = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_valve1.setGeometry(QtCore.QRect(30, 340, 111, 16))
        self.label_sysinf_ace_valve1.setObjectName(_fromUtf8("label_sysinf_ace_valve1"))
        self.label_sysinf_ace_valve1_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_valve1_val.setGeometry(QtCore.QRect(150, 340, 59, 15))
        self.label_sysinf_ace_valve1_val.setObjectName(_fromUtf8("label_sysinf_ace_valve1_val"))
        self.label_sysinf_ace_valve2_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_valve2_val.setGeometry(QtCore.QRect(310, 340, 59, 15))
        self.label_sysinf_ace_valve2_val.setObjectName(_fromUtf8("label_sysinf_ace_valve2_val"))
        self.label_sysinf_ace_valve2 = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_valve2.setGeometry(QtCore.QRect(220, 340, 71, 16))
        self.label_sysinf_ace_valve2.setObjectName(_fromUtf8("label_sysinf_ace_valve2"))
        self.label_sysinf_ace_valve4 = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_valve4.setGeometry(QtCore.QRect(220, 360, 71, 16))
        self.label_sysinf_ace_valve4.setObjectName(_fromUtf8("label_sysinf_ace_valve4"))
        self.label_sysinf_ace_valve3_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_valve3_val.setGeometry(QtCore.QRect(150, 360, 59, 15))
        self.label_sysinf_ace_valve3_val.setObjectName(_fromUtf8("label_sysinf_ace_valve3_val"))
        self.label_sysinf_ace_valve4_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_valve4_val.setGeometry(QtCore.QRect(310, 360, 59, 15))
        self.label_sysinf_ace_valve4_val.setObjectName(_fromUtf8("label_sysinf_ace_valve4_val"))
        self.label_sysinf_ace_valve3 = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_valve3.setGeometry(QtCore.QRect(30, 360, 111, 16))
        self.label_sysinf_ace_valve3.setObjectName(_fromUtf8("label_sysinf_ace_valve3"))
        self.label_sysinf_ace_transport_counter_val = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_transport_counter_val.setGeometry(QtCore.QRect(150, 380, 59, 15))
        self.label_sysinf_ace_transport_counter_val.setObjectName(_fromUtf8("label_sysinf_ace_transport_counter_val"))
        self.label_sysinf_ace_transport_counter = QtGui.QLabel(self.tab)
        self.label_sysinf_ace_transport_counter.setGeometry(QtCore.QRect(30, 380, 111, 16))
        self.label_sysinf_ace_transport_counter.setObjectName(_fromUtf8("label_sysinf_ace_transport_counter"))
        self.label_sysinf_hpd_valvel = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_valvel.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.label_sysinf_hpd_valvel.setObjectName(_fromUtf8("label_sysinf_hpd_valvel"))
        self.label_sysinf_hpd_valvel_val = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_valvel_val.setGeometry(QtCore.QRect(150, 90, 59, 15))
        self.label_sysinf_hpd_valvel_val.setObjectName(_fromUtf8("label_sysinf_hpd_valvel_val"))
        self.label_sysinf_hpd_valver = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_valver.setGeometry(QtCore.QRect(220, 90, 71, 16))
        self.label_sysinf_hpd_valver.setObjectName(_fromUtf8("label_sysinf_hpd_valver"))
        self.label_sysinf_hpd_valver_val = QtGui.QLabel(self.tab)
        self.label_sysinf_hpd_valver_val.setGeometry(QtCore.QRect(310, 90, 59, 15))
        self.label_sysinf_hpd_valver_val.setObjectName(_fromUtf8("label_sysinf_hpd_valver_val"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.pushButton_hpd_panic = QtGui.QPushButton(self.centralwidget)
        self.pushButton_hpd_panic.setGeometry(QtCore.QRect(0, 550, 71, 27))
        self.pushButton_hpd_panic.setObjectName(_fromUtf8("pushButton_hpd_panic"))
        self.pushButton_ace_panic = QtGui.QPushButton(self.centralwidget)
        self.pushButton_ace_panic.setGeometry(QtCore.QRect(70, 550, 71, 27))
        self.pushButton_ace_panic.setObjectName(_fromUtf8("pushButton_ace_panic"))
        self.pushButton_panic = QtGui.QPushButton(self.centralwidget)
        self.pushButton_panic.setGeometry(QtCore.QRect(140, 550, 71, 27))
        self.pushButton_panic.setObjectName(_fromUtf8("pushButton_panic"))
        self.pushButton_clearqueue = QtGui.QPushButton(self.centralwidget)
        self.pushButton_clearqueue.setGeometry(QtCore.QRect(620, 550, 91, 27))
        self.pushButton_clearqueue.setObjectName(_fromUtf8("pushButton_clearqueue"))
        self.pushButton_viewqueue = QtGui.QPushButton(self.centralwidget)
        self.pushButton_viewqueue.setGeometry(QtCore.QRect(710, 550, 91, 27))
        self.pushButton_viewqueue.setObjectName(_fromUtf8("pushButton_viewqueue"))
        self.label_queuesize = QtGui.QLabel(self.centralwidget)
        self.label_queuesize.setGeometry(QtCore.QRect(460, 555, 81, 21))
        self.label_queuesize.setObjectName(_fromUtf8("label_queuesize"))
        self.label_queuesize_val = QtGui.QLabel(self.centralwidget)
        self.label_queuesize_val.setGeometry(QtCore.QRect(535, 549, 31, 31))
        self.label_queuesize_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_queuesize_val.setObjectName(_fromUtf8("label_queuesize_val"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuProsper = QtGui.QMenu(self.menubar)
        self.menuProsper.setObjectName(_fromUtf8("menuProsper"))
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        self.menuConfiguration.setObjectName(_fromUtf8("menuConfiguration"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionEdit = QtGui.QAction(MainWindow)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionManual_control = QtGui.QAction(MainWindow)
        self.actionManual_control.setCheckable(True)
        self.actionManual_control.setObjectName(_fromUtf8("actionManual_control"))
        self.actionAutomation = QtGui.QAction(MainWindow)
        self.actionAutomation.setCheckable(True)
        self.actionAutomation.setObjectName(_fromUtf8("actionAutomation"))
        self.actionSystem_view = QtGui.QAction(MainWindow)
        self.actionSystem_view.setCheckable(True)
        self.actionSystem_view.setObjectName(_fromUtf8("actionSystem_view"))
        self.actionSchematic_view = QtGui.QAction(MainWindow)
        self.actionSchematic_view.setCheckable(True)
        self.actionSchematic_view.setObjectName(_fromUtf8("actionSchematic_view"))
        self.actionDebug = QtGui.QAction(MainWindow)
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.actionSimulation_mode = QtGui.QAction(MainWindow)
        self.actionSimulation_mode.setObjectName(_fromUtf8("actionSimulation_mode"))
        self.actionReset_ACE = QtGui.QAction(MainWindow)
        self.actionReset_ACE.setObjectName(_fromUtf8("actionReset_ACE"))
        self.actionReset_HPD = QtGui.QAction(MainWindow)
        self.actionReset_HPD.setObjectName(_fromUtf8("actionReset_HPD"))
        self.actionReset_PUMP = QtGui.QAction(MainWindow)
        self.actionReset_PUMP.setObjectName(_fromUtf8("actionReset_PUMP"))
        self.actionReset_ALL = QtGui.QAction(MainWindow)
        self.actionReset_ALL.setObjectName(_fromUtf8("actionReset_ALL"))
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.menuProsper.addSeparator()
        self.menuProsper.addAction(self.actionQuit)
        self.menuConfiguration.addAction(self.actionEdit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLog)
        self.menubar.addAction(self.menuProsper.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hpdl_dispense.setText(QtGui.QApplication.translate("MainWindow", "Dispense", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Pressure limit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hpdl_aspirate.setText(QtGui.QApplication.translate("MainWindow", "Aspirate", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valvel.setItemText(0, QtGui.QApplication.translate("MainWindow", "1-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valvel.setItemText(1, QtGui.QApplication.translate("MainWindow", "2-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valvel.setItemText(2, QtGui.QApplication.translate("MainWindow", "3-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valvel.setItemText(3, QtGui.QApplication.translate("MainWindow", "4-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valvel.setItemText(4, QtGui.QApplication.translate("MainWindow", "5-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valvel.setItemText(5, QtGui.QApplication.translate("MainWindow", "6-7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hpdr_dispense.setText(QtGui.QApplication.translate("MainWindow", "Dispense", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hpdr_aspirate.setText(QtGui.QApplication.translate("MainWindow", "Aspirate", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valver.setItemText(0, QtGui.QApplication.translate("MainWindow", "1-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valver.setItemText(1, QtGui.QApplication.translate("MainWindow", "2-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valver.setItemText(2, QtGui.QApplication.translate("MainWindow", "3-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valver.setItemText(3, QtGui.QApplication.translate("MainWindow", "4-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valver.setItemText(4, QtGui.QApplication.translate("MainWindow", "5-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valver.setItemText(5, QtGui.QApplication.translate("MainWindow", "6-7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve1.setItemText(0, QtGui.QApplication.translate("MainWindow", "1-2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve1.setItemText(1, QtGui.QApplication.translate("MainWindow", "2-3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve2.setItemText(0, QtGui.QApplication.translate("MainWindow", "1-2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve2.setItemText(1, QtGui.QApplication.translate("MainWindow", "2-3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve3.setItemText(0, QtGui.QApplication.translate("MainWindow", "1-2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve3.setItemText(1, QtGui.QApplication.translate("MainWindow", "2-3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve4.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve4.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve4.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve4.setItemText(3, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve4.setItemText(4, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve4.setItemText(5, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve4.setItemText(6, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_valve4.setItemText(7, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "HPD-L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "HPD-R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Valves", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Clamps and gripper", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ace_getback.setText(QtGui.QApplication.translate("MainWindow", "Get cartridges back", None, QtGui.QApplication.UnicodeUTF8))
        self.label_trays.setText(QtGui.QApplication.translate("MainWindow", "Trays", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tray_load.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tray_unload.setText(QtGui.QApplication.translate("MainWindow", "Unload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Pressure limit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_acel_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_acel_close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_acer_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_acer_close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_acel_init.setText(QtGui.QApplication.translate("MainWindow", "Init", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_acel_default.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_acer_init.setText(QtGui.QApplication.translate("MainWindow", "Init", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_acer_default.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_trays_2.setText(QtGui.QApplication.translate("MainWindow", "Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_OUT1.setText(QtGui.QApplication.translate("MainWindow", "N2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_OUT2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_OUT3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_OUT4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_trays_3.setText(QtGui.QApplication.translate("MainWindow", "Pump", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pumponoff.setText(QtGui.QApplication.translate("MainWindow", "ON/OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_manual), QtGui.QApplication.translate("MainWindow", "Manual control", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Automation", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_hpdl.setFormat(QtGui.QApplication.translate("MainWindow", "%v", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_hpdr.setFormat(QtGui.QApplication.translate("MainWindow", "%v", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_IN.setText(QtGui.QApplication.translate("MainWindow", "N2 Pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_systemview), QtGui.QApplication.translate("MainWindow", "System view", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd.setText(QtGui.QApplication.translate("MainWindow", "HPD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace.setText(QtGui.QApplication.translate("MainWindow", "ACE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_MCCB.setText(QtGui.QApplication.translate("MainWindow", "MCCB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_transport.setText(QtGui.QApplication.translate("MainWindow", "Transport Module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_clampL.setText(QtGui.QApplication.translate("MainWindow", "ClampL-Module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_clampR.setText(QtGui.QApplication.translate("MainWindow", "ClampR-Module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_ISS.setText(QtGui.QApplication.translate("MainWindow", "ISS module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_RF.setText(QtGui.QApplication.translate("MainWindow", "RF module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_TASPE.setText(QtGui.QApplication.translate("MainWindow", "TASPE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_feeder.setText(QtGui.QApplication.translate("MainWindow", "Feeder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_MPV.setText(QtGui.QApplication.translate("MainWindow", "MPV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_MCCB.setText(QtGui.QApplication.translate("MainWindow", "MCCB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_SSM.setText(QtGui.QApplication.translate("MainWindow", "SSM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_dispenserL.setText(QtGui.QApplication.translate("MainWindow", "DispenserL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_dispenserR.setText(QtGui.QApplication.translate("MainWindow", "DispenserR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_MCCB_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_dispenserL_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_dispenserR_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_SSM_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_MCCB_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_ISS_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_RF_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_transport_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_clampL_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_clampR_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_MPV_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_TASPE_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_feeder_val.setText(QtGui.QApplication.translate("MainWindow", "v 0.42", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_sys_inf.setText(QtGui.QApplication.translate("MainWindow", "Get values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_valve1.setText(QtGui.QApplication.translate("MainWindow", "Valve 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_valve1_val.setText(QtGui.QApplication.translate("MainWindow", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_valve2_val.setText(QtGui.QApplication.translate("MainWindow", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_valve2.setText(QtGui.QApplication.translate("MainWindow", "Valve 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_valve4.setText(QtGui.QApplication.translate("MainWindow", "Valve 4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_valve3_val.setText(QtGui.QApplication.translate("MainWindow", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_valve4_val.setText(QtGui.QApplication.translate("MainWindow", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_valve3.setText(QtGui.QApplication.translate("MainWindow", "Valve 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_transport_counter_val.setText(QtGui.QApplication.translate("MainWindow", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_ace_transport_counter.setText(QtGui.QApplication.translate("MainWindow", "Transport", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_valvel.setText(QtGui.QApplication.translate("MainWindow", "ValveL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_valvel_val.setText(QtGui.QApplication.translate("MainWindow", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_valver.setText(QtGui.QApplication.translate("MainWindow", "ValveR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sysinf_hpd_valver_val.setText(QtGui.QApplication.translate("MainWindow", "42", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "System informations", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hpd_panic.setText(QtGui.QApplication.translate("MainWindow", "HPD Panic", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ace_panic.setText(QtGui.QApplication.translate("MainWindow", "ACE Panic", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_panic.setText(QtGui.QApplication.translate("MainWindow", "Panic", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clearqueue.setText(QtGui.QApplication.translate("MainWindow", "Clear queue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_viewqueue.setText(QtGui.QApplication.translate("MainWindow", "View queue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_queuesize.setText(QtGui.QApplication.translate("MainWindow", "Queue size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_queuesize_val.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProsper.setTitle(QtGui.QApplication.translate("MainWindow", "Prosper", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfiguration.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual_control.setText(QtGui.QApplication.translate("MainWindow", "Manual control", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAutomation.setText(QtGui.QApplication.translate("MainWindow", "Automation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSystem_view.setText(QtGui.QApplication.translate("MainWindow", "System view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSchematic_view.setText(QtGui.QApplication.translate("MainWindow", "Schematic view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug.setText(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation_mode.setText(QtGui.QApplication.translate("MainWindow", "Simulation mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_ACE.setText(QtGui.QApplication.translate("MainWindow", "Reset ACE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_HPD.setText(QtGui.QApplication.translate("MainWindow", "Reset HPD", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_PUMP.setText(QtGui.QApplication.translate("MainWindow", "Reset PUMP", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_ALL.setText(QtGui.QApplication.translate("MainWindow", "Reset ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))

import prosper_rc
