# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prosper_dialog_racks.ui'
#
# Created: Fri Mar 16 19:38:41 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog_racks(object):
    def setupUi(self, Dialog_racks):
        Dialog_racks.setObjectName(_fromUtf8("Dialog_racks"))
        Dialog_racks.resize(630, 530)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_racks)
        self.buttonBox.setGeometry(QtCore.QRect(0, 500, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.rack_left = QtGui.QTableWidget(Dialog_racks)
        self.rack_left.setGeometry(QtCore.QRect(0, 20, 271, 391))
        self.rack_left.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rack_left.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rack_left.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rack_left.setAlternatingRowColors(False)
        self.rack_left.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.rack_left.setGridStyle(QtCore.Qt.DashLine)
        self.rack_left.setRowCount(12)
        self.rack_left.setColumnCount(8)
        self.rack_left.setObjectName(_fromUtf8("rack_left"))
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(7, item)
        self.rack_left.horizontalHeader().setCascadingSectionResizes(False)
        self.rack_left.horizontalHeader().setDefaultSectionSize(30)
        self.rack_left.horizontalHeader().setMinimumSectionSize(30)
        self.rack_left.verticalHeader().setDefaultSectionSize(30)
        self.rack_left.verticalHeader().setMinimumSectionSize(30)
        self.rack_right = QtGui.QTableWidget(Dialog_racks)
        self.rack_right.setGeometry(QtCore.QRect(360, 20, 271, 391))
        self.rack_right.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rack_right.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rack_right.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rack_right.setAlternatingRowColors(False)
        self.rack_right.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.rack_right.setGridStyle(QtCore.Qt.DashLine)
        self.rack_right.setRowCount(12)
        self.rack_right.setColumnCount(8)
        self.rack_right.setObjectName(_fromUtf8("rack_right"))
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(7, item)
        self.rack_right.horizontalHeader().setCascadingSectionResizes(False)
        self.rack_right.horizontalHeader().setDefaultSectionSize(30)
        self.rack_right.horizontalHeader().setMinimumSectionSize(30)
        self.rack_right.verticalHeader().setDefaultSectionSize(30)
        self.rack_right.verticalHeader().setMinimumSectionSize(30)
        self.pushButton_clear_left = QtGui.QPushButton(Dialog_racks)
        self.pushButton_clear_left.setGeometry(QtCore.QRect(90, 410, 92, 27))
        self.pushButton_clear_left.setObjectName(_fromUtf8("pushButton_clear_left"))
        self.pushButton_clear_right = QtGui.QPushButton(Dialog_racks)
        self.pushButton_clear_right.setGeometry(QtCore.QRect(460, 410, 92, 27))
        self.pushButton_clear_right.setObjectName(_fromUtf8("pushButton_clear_right"))
        self.pushButton_clear_both = QtGui.QPushButton(Dialog_racks)
        self.pushButton_clear_both.setGeometry(QtCore.QRect(270, 410, 92, 27))
        self.pushButton_clear_both.setObjectName(_fromUtf8("pushButton_clear_both"))

        self.retranslateUi(Dialog_racks)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_racks.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_racks.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_racks)

    def retranslateUi(self, Dialog_racks):
        Dialog_racks.setWindowTitle(QtGui.QApplication.translate("Dialog_racks", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "12", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "11", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "10", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "A", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "B", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "C", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "D", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "E", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "F", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "G", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "H", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "12", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "11", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "10", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "A", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "B", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "C", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "D", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "E", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "F", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "G", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog_racks", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear_left.setText(QtGui.QApplication.translate("Dialog_racks", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear_right.setText(QtGui.QApplication.translate("Dialog_racks", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear_both.setText(QtGui.QApplication.translate("Dialog_racks", "Clear both", None, QtGui.QApplication.UnicodeUTF8))

