# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prosper_dialog_add_action.ui'
#
# Created: Fri Apr  6 17:35:54 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog_add_action(object):
    def setupUi(self, Dialog_add_action):
        Dialog_add_action.setObjectName(_fromUtf8("Dialog_add_action"))
        Dialog_add_action.resize(777, 503)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_add_action)
        self.buttonBox.setGeometry(QtCore.QRect(590, 470, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.rack_left = QtGui.QTableWidget(Dialog_add_action)
        self.rack_left.setGeometry(QtCore.QRect(0, 20, 271, 391))
        self.rack_left.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rack_left.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rack_left.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rack_left.setAlternatingRowColors(False)
        self.rack_left.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.rack_left.setGridStyle(QtCore.Qt.DashLine)
        self.rack_left.setRowCount(12)
        self.rack_left.setColumnCount(8)
        self.rack_left.setObjectName(_fromUtf8("rack_left"))
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.rack_left.setHorizontalHeaderItem(7, item)
        self.rack_left.horizontalHeader().setCascadingSectionResizes(False)
        self.rack_left.horizontalHeader().setDefaultSectionSize(30)
        self.rack_left.horizontalHeader().setMinimumSectionSize(30)
        self.rack_left.verticalHeader().setDefaultSectionSize(30)
        self.rack_left.verticalHeader().setMinimumSectionSize(30)
        self.rack_right = QtGui.QTableWidget(Dialog_add_action)
        self.rack_right.setGeometry(QtCore.QRect(270, 20, 271, 391))
        self.rack_right.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rack_right.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rack_right.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rack_right.setAlternatingRowColors(False)
        self.rack_right.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.rack_right.setGridStyle(QtCore.Qt.DashLine)
        self.rack_right.setRowCount(12)
        self.rack_right.setColumnCount(8)
        self.rack_right.setObjectName(_fromUtf8("rack_right"))
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.rack_right.setHorizontalHeaderItem(7, item)
        self.rack_right.horizontalHeader().setCascadingSectionResizes(False)
        self.rack_right.horizontalHeader().setDefaultSectionSize(30)
        self.rack_right.horizontalHeader().setMinimumSectionSize(30)
        self.rack_right.verticalHeader().setDefaultSectionSize(30)
        self.rack_right.verticalHeader().setMinimumSectionSize(30)
        self.pushButton_clear_left = QtGui.QPushButton(Dialog_add_action)
        self.pushButton_clear_left.setGeometry(QtCore.QRect(110, 420, 92, 27))
        self.pushButton_clear_left.setObjectName(_fromUtf8("pushButton_clear_left"))
        self.pushButton_clear_right = QtGui.QPushButton(Dialog_add_action)
        self.pushButton_clear_right.setGeometry(QtCore.QRect(340, 420, 92, 27))
        self.pushButton_clear_right.setObjectName(_fromUtf8("pushButton_clear_right"))
        self.pushButton_clear_both = QtGui.QPushButton(Dialog_add_action)
        self.pushButton_clear_both.setGeometry(QtCore.QRect(225, 420, 90, 27))
        self.pushButton_clear_both.setObjectName(_fromUtf8("pushButton_clear_both"))
        self.comboBox_action = QtGui.QComboBox(Dialog_add_action)
        self.comboBox_action.setGeometry(QtCore.QRect(550, 20, 221, 25))
        self.comboBox_action.setObjectName(_fromUtf8("comboBox_action"))
        self.comboBox_action.addItem(_fromUtf8(""))
        self.comboBox_action.addItem(_fromUtf8(""))
        self.comboBox_action.addItem(_fromUtf8(""))
        self.line = QtGui.QFrame(Dialog_add_action)
        self.line.setGeometry(QtCore.QRect(80, 490, 381, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.tabWidget = QtGui.QTabWidget(Dialog_add_action)
        self.tabWidget.setGeometry(QtCore.QRect(550, 50, 221, 261))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_flow = QtGui.QWidget()
        self.tab_flow.setObjectName(_fromUtf8("tab_flow"))
        self.spinBox_solvent1volume = QtGui.QSpinBox(self.tab_flow)
        self.spinBox_solvent1volume.setGeometry(QtCore.QRect(120, 40, 91, 25))
        self.spinBox_solvent1volume.setObjectName(_fromUtf8("spinBox_solvent1volume"))
        self.label_solvent1volume = QtGui.QLabel(self.tab_flow)
        self.label_solvent1volume.setGeometry(QtCore.QRect(0, 40, 121, 21))
        self.label_solvent1volume.setObjectName(_fromUtf8("label_solvent1volume"))
        self.spinBox_solvent2volume = QtGui.QSpinBox(self.tab_flow)
        self.spinBox_solvent2volume.setGeometry(QtCore.QRect(120, 150, 91, 25))
        self.spinBox_solvent2volume.setObjectName(_fromUtf8("spinBox_solvent2volume"))
        self.label_solvent2volume = QtGui.QLabel(self.tab_flow)
        self.label_solvent2volume.setGeometry(QtCore.QRect(0, 150, 121, 21))
        self.label_solvent2volume.setObjectName(_fromUtf8("label_solvent2volume"))
        self.comboBox_solvent1 = QtGui.QComboBox(self.tab_flow)
        self.comboBox_solvent1.setGeometry(QtCore.QRect(120, 10, 91, 25))
        self.comboBox_solvent1.setObjectName(_fromUtf8("comboBox_solvent1"))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.comboBox_solvent1.addItem(_fromUtf8(""))
        self.label_solvent1 = QtGui.QLabel(self.tab_flow)
        self.label_solvent1.setGeometry(QtCore.QRect(0, 10, 91, 21))
        self.label_solvent1.setObjectName(_fromUtf8("label_solvent1"))
        self.label_solvent2 = QtGui.QLabel(self.tab_flow)
        self.label_solvent2.setGeometry(QtCore.QRect(0, 120, 121, 21))
        self.label_solvent2.setObjectName(_fromUtf8("label_solvent2"))
        self.comboBox_solvent2 = QtGui.QComboBox(self.tab_flow)
        self.comboBox_solvent2.setGeometry(QtCore.QRect(120, 120, 91, 25))
        self.comboBox_solvent2.setObjectName(_fromUtf8("comboBox_solvent2"))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.comboBox_solvent2.addItem(_fromUtf8(""))
        self.spinBox_solvent1flow = QtGui.QSpinBox(self.tab_flow)
        self.spinBox_solvent1flow.setGeometry(QtCore.QRect(120, 70, 91, 25))
        self.spinBox_solvent1flow.setObjectName(_fromUtf8("spinBox_solvent1flow"))
        self.label_solvent1flow = QtGui.QLabel(self.tab_flow)
        self.label_solvent1flow.setGeometry(QtCore.QRect(0, 70, 91, 21))
        self.label_solvent1flow.setObjectName(_fromUtf8("label_solvent1flow"))
        self.label_solvent2flow = QtGui.QLabel(self.tab_flow)
        self.label_solvent2flow.setGeometry(QtCore.QRect(0, 180, 121, 21))
        self.label_solvent2flow.setObjectName(_fromUtf8("label_solvent2flow"))
        self.spinBox_solvent2flow = QtGui.QSpinBox(self.tab_flow)
        self.spinBox_solvent2flow.setGeometry(QtCore.QRect(120, 180, 91, 25))
        self.spinBox_solvent2flow.setObjectName(_fromUtf8("spinBox_solvent2flow"))
        self.tabWidget.addTab(self.tab_flow, _fromUtf8(""))
        self.tab_dry = QtGui.QWidget()
        self.tab_dry.setObjectName(_fromUtf8("tab_dry"))
        self.label_drytime = QtGui.QLabel(self.tab_dry)
        self.label_drytime.setGeometry(QtCore.QRect(0, 20, 91, 21))
        self.label_drytime.setObjectName(_fromUtf8("label_drytime"))
        self.spinBox_drytime = QtGui.QSpinBox(self.tab_dry)
        self.spinBox_drytime.setGeometry(QtCore.QRect(120, 20, 91, 25))
        self.spinBox_drytime.setObjectName(_fromUtf8("spinBox_drytime"))
        self.tabWidget.addTab(self.tab_dry, _fromUtf8(""))
        self.tab_input2spe = QtGui.QWidget()
        self.tab_input2spe.setObjectName(_fromUtf8("tab_input2spe"))
        self.spinBox_cycles_i2s = QtGui.QSpinBox(self.tab_input2spe)
        self.spinBox_cycles_i2s.setGeometry(QtCore.QRect(120, 0, 91, 21))
        self.spinBox_cycles_i2s.setObjectName(_fromUtf8("spinBox_cycles_i2s"))
        self.label_cycles_i2s = QtGui.QLabel(self.tab_input2spe)
        self.label_cycles_i2s.setGeometry(QtCore.QRect(0, 0, 91, 21))
        self.label_cycles_i2s.setObjectName(_fromUtf8("label_cycles_i2s"))
        self.label_pushsolvent_i2s = QtGui.QLabel(self.tab_input2spe)
        self.label_pushsolvent_i2s.setGeometry(QtCore.QRect(0, 30, 91, 21))
        self.label_pushsolvent_i2s.setObjectName(_fromUtf8("label_pushsolvent_i2s"))
        self.comboBox_pushsolvent_i2s = QtGui.QComboBox(self.tab_input2spe)
        self.comboBox_pushsolvent_i2s.setGeometry(QtCore.QRect(120, 30, 91, 21))
        self.comboBox_pushsolvent_i2s.setObjectName(_fromUtf8("comboBox_pushsolvent_i2s"))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.comboBox_pushsolvent_i2s.addItem(_fromUtf8(""))
        self.label_looploadvolume_i2s = QtGui.QLabel(self.tab_input2spe)
        self.label_looploadvolume_i2s.setGeometry(QtCore.QRect(0, 120, 121, 21))
        self.label_looploadvolume_i2s.setObjectName(_fromUtf8("label_looploadvolume_i2s"))
        self.spinBox_looploadvolume_i2s = QtGui.QSpinBox(self.tab_input2spe)
        self.spinBox_looploadvolume_i2s.setGeometry(QtCore.QRect(120, 120, 91, 21))
        self.spinBox_looploadvolume_i2s.setObjectName(_fromUtf8("spinBox_looploadvolume_i2s"))
        self.checkBox_askcycles_i2s = QtGui.QCheckBox(self.tab_input2spe)
        self.checkBox_askcycles_i2s.setGeometry(QtCore.QRect(0, 210, 201, 20))
        self.checkBox_askcycles_i2s.setObjectName(_fromUtf8("checkBox_askcycles_i2s"))
        self.spinBox_loopinjectvolume_i2s = QtGui.QSpinBox(self.tab_input2spe)
        self.spinBox_loopinjectvolume_i2s.setGeometry(QtCore.QRect(120, 150, 91, 21))
        self.spinBox_loopinjectvolume_i2s.setObjectName(_fromUtf8("spinBox_loopinjectvolume_i2s"))
        self.label_loopinjectvolume_i2s = QtGui.QLabel(self.tab_input2spe)
        self.label_loopinjectvolume_i2s.setGeometry(QtCore.QRect(0, 150, 121, 21))
        self.label_loopinjectvolume_i2s.setObjectName(_fromUtf8("label_loopinjectvolume_i2s"))
        self.label_pushflowrate_i2s = QtGui.QLabel(self.tab_input2spe)
        self.label_pushflowrate_i2s.setGeometry(QtCore.QRect(0, 60, 101, 21))
        self.label_pushflowrate_i2s.setObjectName(_fromUtf8("label_pushflowrate_i2s"))
        self.spinBox_pushflowrate_i2s = QtGui.QSpinBox(self.tab_input2spe)
        self.spinBox_pushflowrate_i2s.setGeometry(QtCore.QRect(120, 60, 91, 21))
        self.spinBox_pushflowrate_i2s.setObjectName(_fromUtf8("spinBox_pushflowrate_i2s"))
        self.label_inputflowrate_i2s = QtGui.QLabel(self.tab_input2spe)
        self.label_inputflowrate_i2s.setGeometry(QtCore.QRect(0, 90, 101, 21))
        self.label_inputflowrate_i2s.setObjectName(_fromUtf8("label_inputflowrate_i2s"))
        self.spinBox_inputflowrate_i2s = QtGui.QSpinBox(self.tab_input2spe)
        self.spinBox_inputflowrate_i2s.setGeometry(QtCore.QRect(120, 90, 91, 21))
        self.spinBox_inputflowrate_i2s.setObjectName(_fromUtf8("spinBox_inputflowrate_i2s"))
        self.spinBox_pause_i2s = QtGui.QSpinBox(self.tab_input2spe)
        self.spinBox_pause_i2s.setGeometry(QtCore.QRect(120, 180, 91, 21))
        self.spinBox_pause_i2s.setObjectName(_fromUtf8("spinBox_pause_i2s"))
        self.label_pause_i2s = QtGui.QLabel(self.tab_input2spe)
        self.label_pause_i2s.setGeometry(QtCore.QRect(0, 180, 121, 21))
        self.label_pause_i2s.setObjectName(_fromUtf8("label_pause_i2s"))
        self.tabWidget.addTab(self.tab_input2spe, _fromUtf8(""))
        self.lineEdit_comment = QtGui.QLineEdit(Dialog_add_action)
        self.lineEdit_comment.setGeometry(QtCore.QRect(90, 470, 361, 25))
        self.lineEdit_comment.setObjectName(_fromUtf8("lineEdit_comment"))
        self.label_2 = QtGui.QLabel(Dialog_add_action)
        self.label_2.setGeometry(QtCore.QRect(240, 450, 71, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_save = QtGui.QPushButton(Dialog_add_action)
        self.pushButton_save.setGeometry(QtCore.QRect(550, 430, 91, 27))
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.pushButton_load = QtGui.QPushButton(Dialog_add_action)
        self.pushButton_load.setGeometry(QtCore.QRect(550, 400, 91, 27))
        self.pushButton_load.setObjectName(_fromUtf8("pushButton_load"))
        self.pushButton_loaddefault = QtGui.QPushButton(Dialog_add_action)
        self.pushButton_loaddefault.setGeometry(QtCore.QRect(660, 400, 111, 27))
        self.pushButton_loaddefault.setObjectName(_fromUtf8("pushButton_loaddefault"))
        self.pushButton_savedefault = QtGui.QPushButton(Dialog_add_action)
        self.pushButton_savedefault.setGeometry(QtCore.QRect(660, 430, 111, 27))
        self.pushButton_savedefault.setObjectName(_fromUtf8("pushButton_savedefault"))
        self.label_currentmethod_val = QtGui.QLabel(Dialog_add_action)
        self.label_currentmethod_val.setGeometry(QtCore.QRect(570, 380, 201, 20))
        self.label_currentmethod_val.setObjectName(_fromUtf8("label_currentmethod_val"))
        self.label_currentmethod = QtGui.QLabel(Dialog_add_action)
        self.label_currentmethod.setGeometry(QtCore.QRect(550, 365, 121, 16))
        self.label_currentmethod.setObjectName(_fromUtf8("label_currentmethod"))
        self.line_2 = QtGui.QFrame(Dialog_add_action)
        self.line_2.setGeometry(QtCore.QRect(540, 450, 241, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(Dialog_add_action)
        self.line_3.setGeometry(QtCore.QRect(530, 410, 20, 51))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.checkBox_askcartridges = QtGui.QCheckBox(Dialog_add_action)
        self.checkBox_askcartridges.setGeometry(QtCore.QRect(550, 340, 211, 20))
        self.checkBox_askcartridges.setObjectName(_fromUtf8("checkBox_askcartridges"))
        self.comboBox_output = QtGui.QComboBox(Dialog_add_action)
        self.comboBox_output.setGeometry(QtCore.QRect(670, 315, 91, 25))
        self.comboBox_output.setObjectName(_fromUtf8("comboBox_output"))
        self.comboBox_output.addItem(_fromUtf8(""))
        self.comboBox_output.addItem(_fromUtf8(""))
        self.label_output = QtGui.QLabel(Dialog_add_action)
        self.label_output.setGeometry(QtCore.QRect(550, 315, 121, 21))
        self.label_output.setObjectName(_fromUtf8("label_output"))

        self.retranslateUi(Dialog_add_action)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog_add_action.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog_add_action.reject)
        QtCore.QObject.connect(self.comboBox_action, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.tabWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog_add_action)

    def retranslateUi(self, Dialog_add_action):
        Dialog_add_action.setWindowTitle(QtGui.QApplication.translate("Dialog_add_action", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "12", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "11", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "10", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.verticalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "A", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "B", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "C", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "D", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "E", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "F", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "G", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_left.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "H", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "12", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "11", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "10", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "9", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "8", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "7", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "6", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "5", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(8)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "4", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(9)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "3", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(10)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.verticalHeaderItem(11)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "A", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "B", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "C", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "D", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "E", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "F", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "G", None, QtGui.QApplication.UnicodeUTF8))
        item = self.rack_right.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("Dialog_add_action", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear_left.setText(QtGui.QApplication.translate("Dialog_add_action", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear_right.setText(QtGui.QApplication.translate("Dialog_add_action", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear_both.setText(QtGui.QApplication.translate("Dialog_add_action", "Clear both", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_action.setItemText(0, QtGui.QApplication.translate("Dialog_add_action", "Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_action.setItemText(1, QtGui.QApplication.translate("Dialog_add_action", "Dry", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_action.setItemText(2, QtGui.QApplication.translate("Dialog_add_action", "Input to SPE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_solvent1volume.setText(QtGui.QApplication.translate("Dialog_add_action", "Solvent 1 volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_solvent2volume.setText(QtGui.QApplication.translate("Dialog_add_action", "Solvent 2 volume", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(0, QtGui.QApplication.translate("Dialog_add_action", "Left 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(1, QtGui.QApplication.translate("Dialog_add_action", "Left 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(2, QtGui.QApplication.translate("Dialog_add_action", "Left 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(3, QtGui.QApplication.translate("Dialog_add_action", "Left 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(4, QtGui.QApplication.translate("Dialog_add_action", "Left 5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(5, QtGui.QApplication.translate("Dialog_add_action", "Left 6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(6, QtGui.QApplication.translate("Dialog_add_action", "Right 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(7, QtGui.QApplication.translate("Dialog_add_action", "Right 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(8, QtGui.QApplication.translate("Dialog_add_action", "Right 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(9, QtGui.QApplication.translate("Dialog_add_action", "Right 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(10, QtGui.QApplication.translate("Dialog_add_action", "Right 5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent1.setItemText(11, QtGui.QApplication.translate("Dialog_add_action", "Right 6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_solvent1.setText(QtGui.QApplication.translate("Dialog_add_action", "Solvent 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_solvent2.setText(QtGui.QApplication.translate("Dialog_add_action", "Solvent 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(0, QtGui.QApplication.translate("Dialog_add_action", "Left 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(1, QtGui.QApplication.translate("Dialog_add_action", "Left 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(2, QtGui.QApplication.translate("Dialog_add_action", "Left 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(3, QtGui.QApplication.translate("Dialog_add_action", "Left 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(4, QtGui.QApplication.translate("Dialog_add_action", "Left 5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(5, QtGui.QApplication.translate("Dialog_add_action", "Left 6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(6, QtGui.QApplication.translate("Dialog_add_action", "Right 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(7, QtGui.QApplication.translate("Dialog_add_action", "Right 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(8, QtGui.QApplication.translate("Dialog_add_action", "Right 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(9, QtGui.QApplication.translate("Dialog_add_action", "Right 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(10, QtGui.QApplication.translate("Dialog_add_action", "Right 5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_solvent2.setItemText(11, QtGui.QApplication.translate("Dialog_add_action", "Right 6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_solvent1flow.setText(QtGui.QApplication.translate("Dialog_add_action", "Solvent 1 flow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_solvent2flow.setText(QtGui.QApplication.translate("Dialog_add_action", "Solvent 2 flow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_flow), QtGui.QApplication.translate("Dialog_add_action", "Flow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_drytime.setText(QtGui.QApplication.translate("Dialog_add_action", "Dry time", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dry), QtGui.QApplication.translate("Dialog_add_action", "Dry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cycles_i2s.setText(QtGui.QApplication.translate("Dialog_add_action", "Cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pushsolvent_i2s.setText(QtGui.QApplication.translate("Dialog_add_action", "Push solvent", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(0, QtGui.QApplication.translate("Dialog_add_action", "Pump", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(1, QtGui.QApplication.translate("Dialog_add_action", "Left 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(2, QtGui.QApplication.translate("Dialog_add_action", "Left 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(3, QtGui.QApplication.translate("Dialog_add_action", "Left 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(4, QtGui.QApplication.translate("Dialog_add_action", "Left 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(5, QtGui.QApplication.translate("Dialog_add_action", "Left 5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(6, QtGui.QApplication.translate("Dialog_add_action", "Left 6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(7, QtGui.QApplication.translate("Dialog_add_action", "Right 1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(8, QtGui.QApplication.translate("Dialog_add_action", "Right 2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(9, QtGui.QApplication.translate("Dialog_add_action", "Right 3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(10, QtGui.QApplication.translate("Dialog_add_action", "Right 4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(11, QtGui.QApplication.translate("Dialog_add_action", "Right 5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pushsolvent_i2s.setItemText(12, QtGui.QApplication.translate("Dialog_add_action", "Right 6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_looploadvolume_i2s.setText(QtGui.QApplication.translate("Dialog_add_action", "Loop load volume", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_askcycles_i2s.setText(QtGui.QApplication.translate("Dialog_add_action", "Ask user between cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_loopinjectvolume_i2s.setText(QtGui.QApplication.translate("Dialog_add_action", "Loop inject volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pushflowrate_i2s.setText(QtGui.QApplication.translate("Dialog_add_action", "Push flow-rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_inputflowrate_i2s.setText(QtGui.QApplication.translate("Dialog_add_action", "Input flow-rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pause_i2s.setText(QtGui.QApplication.translate("Dialog_add_action", "Pause / cycles", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_input2spe), QtGui.QApplication.translate("Dialog_add_action", "Input2spe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_add_action", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setText(QtGui.QApplication.translate("Dialog_add_action", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_load.setText(QtGui.QApplication.translate("Dialog_add_action", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_loaddefault.setText(QtGui.QApplication.translate("Dialog_add_action", "Load default", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_savedefault.setText(QtGui.QApplication.translate("Dialog_add_action", "Save as default", None, QtGui.QApplication.UnicodeUTF8))
        self.label_currentmethod_val.setText(QtGui.QApplication.translate("Dialog_add_action", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.label_currentmethod.setText(QtGui.QApplication.translate("Dialog_add_action", "Current method:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_askcartridges.setText(QtGui.QApplication.translate("Dialog_add_action", "Ask user between cartridges", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_output.setItemText(0, QtGui.QApplication.translate("Dialog_add_action", "Waste", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_output.setItemText(1, QtGui.QApplication.translate("Dialog_add_action", "Collect", None, QtGui.QApplication.UnicodeUTF8))
        self.label_output.setText(QtGui.QApplication.translate("Dialog_add_action", "Output", None, QtGui.QApplication.UnicodeUTF8))

import prosper_rc
